### ISSUE TITLE
[Development] Livereload sometimes not reflect changes after watch run

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#113]
Got this issue in my office setup
chrome browser return 

livereload.js?port=443:76 WebSocket connection to 'wss://warden-env.test/livereload' failed: Error during WebSocket handshake: Unexpected response code: 502
I expected changes should apply after modify less. But sometimes it's not reflect and go to browser console return above error

Is this problem related with magento version ?

**Comment by davidalger** [comment]
502 Bad Gateway response on the WSS endpoint and/or on `/livereload.js` request typically means `grunt watch` is not listening within the `php-fpm` container.

Have you tried reviewing each of the steps documented here to ensure the env has been setup 100% for LiveReload use? https://docs.warden.dev/configuration/livereload.html

**Comment by mrtuvn** [comment]
@davidalger yes i have already checked that link
run exactly commands in that
Is this setup depend on magento version ? in the step add livereload into env config i'm not sure it's work with current magento (2.3.2)

**Comment by mrtuvn** [comment]
@davidalger 
i got server response 404 for livereload.js
Tried restart containers and re-run grunt but it's doesn't help

**Comment by davidalger** [comment]
You should not need to restart the containers for it to work. They should be starting up with the labels on them so Traefik will route the requests, something like this:
```
    labels:
      traefik.enable: "true"
      traefik.http.routers.exampleproject-livereload.priority: '2'
      traefik.http.routers.exampleproject-livereload.rule: ' (HostRegexp(`{subdomain:.+}.exampleproject.test`)
        || Host(`exampleproject.test`)) && (Path(`/livereload.js`) || Path(`/livereload`))'
      traefik.http.routers.exampleproject-livereload.service: exampleproject-livereload
      traefik.http.routers.exampleproject-livereload.tls: "true"
      traefik.http.services.exampleproject-livereload.loadbalancer.server.port: '35729'
```

You should be able to see these on the php-fpm config in the output of `warden env config` and they result in a router showing up in the Traefik dashboard which you can see here: https://traefik.warden.test/dashboard/#/http/routers?filter=livereload

It would look like this (if you don't see anything there, that's a problem, and you'd probably see a 404 coming from Magento):
![Screen-Shot-2020-03-30-17-24-50 62-HGj2xgKfDg1Q](https://user-images.githubusercontent.com/658281/77967836-93087300-72ab-11ea-9878-66c268e180c8.png)

With these setup, Grunt must be listening on port 35729 within the php-fpm container. If it's not, that would also cause a 404 response. In this case, you're probably seeing a "404 Not Found" string as a response and nothing more.

Hopefully this info will help get you pointed in the right direction. If it doesn't, I'm afraid you'll need to provide more information and perhaps do some digging in your own. Just to be sure, I just ran through the steps outlined at https://docs.warden.dev/environments/initializing.html to setup a completely new M2 environment from scratch, then copied the gruntfile and package.json into place, ran npm install, then ran the grunt commands — all as outlined on the afore mentioned page https://docs.warden.dev/configuration/livereload.html — and then loaded up https://app.exampleproject.test/livereload.js?port=443 in my browser. It worked. My suspicion is there is perhaps something messed up with your grunt configuration, and so grunt is not listening on port 35729 as it should be.
