### ISSUE TITLE
Provide CA cert to Blackfire container

### ISSUE THREAD

**Issue by fooman** [davidalger/warden#145]
When trying to run blackfire via warden against the https secured site via
```
warden env run blackfire-agent blackfire curl https://${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}
```
I ran into untrusted certificate issues.

The below works for me on MacOS:

```
version: "3.5"
services:
    blackfire-agent:
        extra_hosts:
            - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
        volumes:
            - ${WARDEN_SSL_DIR}/rootca/certs/ca.cert.pem:/etc/ssl/certs/ca-certificates.crt:ro
```

It looks like the php-fpm container updates certificates at run time but I wasn't able to figure out a way to cross link just the generated output from the php-fpm container into the blackfire one.
