### ISSUE TITLE
Using "local" environment type possibility [Feature request]

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#159]
The project am working involves Magento2 and angular and these two will work/act as independent projects/platforms. 

Trying to see if I can able to make `local` warden environment type to handle the frontend build loading environment which will going to connect to magento service.

So instead of me running the frontend app under localhost:4200, checking to see way for to run the same under something like `app.w2front.test` 

By having the following warden docker compose config, can able to access files from `app.w2front.test/index.html` [But loading some other URL will not work because of not available url rewrite]

```
version: '3.5'
networks:
  default:
    labels:
      dev.warden.environment.name: w2front
      dev.warden.environment.type: local
services:
  nginx:
    environment:
      NGINX_PUBLIC: /
      NGINX_TEMPLATE: application.conf
      XDEBUG_CONNECT_BACK_HOST: host.docker.internal
    hostname: w2front-nginx
    image: docker.io/wardenenv/nginx:1.16
    labels:
      traefik.enable: "true"
      traefik.http.routers.w2front-nginx.priority: '2'
      traefik.http.routers.w2front-nginx.rule: ' HostRegexp(`{subdomain:.+}.w2front.test`)
        || Host(`w2front.test`)'
      traefik.http.routers.w2front-nginx.tls: "true"
      traefik.http.services.w2front-nginx.loadbalancer.server.port: '80'
    volumes:
      - ./dist/webApp:/var/www/html:delegated
```

Even if I place `application.conf` under `.warden` its not taking any config from this to container.
