### ISSUE TITLE
Blackfire CLI profiling

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#187]
Profiling Magento 2 with the blackfire browser extension works well.
But what is the right way to run the `blackfire` command line tool to profile, for example, `bin/magento` commands?

**Comment by navarr** [comment]
Bad news, there is not yet a way to do so!

I've just reviewed the Blackfire documentation, though, and will be contributing it soon.

Once it's contributed, the way to do so would be to run:

`warden env exec php-blackfire /bin/bash` if you wanted a shell that supports the blackfire command.

**Comment by navarr** [comment]
As a workaround while you wait,

You can add a `.warden/warden-env.yml` with the content:

```yaml
version: "3.5"
services:
  php-blackfire:
    environment:
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
```

Then run a `warden env up -d` to bring your environment back up with the new configuration, and run `warden env exec php-blackfire /bin/bash`, from there, a `sudo su -` and run:

```
mkdir -p /tmp/blackfire \
    && curl -A "Docker" -L https://blackfire.io/api/v1/releases/client/linux_static/amd64 | tar zxp -C /tmp/blackfire \
    && mv /tmp/blackfire/blackfire /usr/bin/blackfire \
    && rm -rf /tmp/blackfire
```

This will install the blackfire client, and then once you drop out of sudo you should be able to run `blackfire run bin/magento`
