### ISSUE TITLE
Add additional container / services

### ISSUE THREAD

**Issue by sebastian-ehrling** [davidalger/warden#193]
Hey

is it possible to add more services like kibana or mysql to a magento 2 enviroment?

**Comment by davidalger** [comment]
@sebastian-ehrling If you'd like to use MySQL instead, the `db` container can be switched to point to the MySQL image by adding the following to the project's `.warden/warden-env.yml ` file:

```
version: "3.5"
services:
  db:
    image: docker.io/wardenenv/mysql:5.7
```

If you already have the project running, you'll probably want to destroy it (including volumes) so MySQL doesn't try and start up with a data volume with MariaDB content: `warden env down -v && warden env up`

The files `.warden/warden-env.yml`, `.warden/warden-env.darwin.yml` and `.warden/warden-env.linux.yml` are merged into the default docker-compose configuration for any `warden env ...` commands. You can put stuff in there, and then use `warden env config` to spit out the full rendered config from docker-compose.

**Comment by sebastian-ehrling** [comment]
@davidalger thank you for your help.
The advise to show the config with the command "warden env config" helped a lot!

**Comment by jomin-jolly** [comment]
May be helpful to add phpmyadmin,

docker pull phpmyadmin

add .warden/warden-env.yml file with the following code,

version: "2"
services:
  phpmyadmin:
    restart: always
    image: docker.io/library/phpmyadmin:latest
    hostname: {{your_host}}-phpmyadmin
    domainname: phpmyadmin.{{your_host}}.test
    ports:
      - 8000:80
    environment:
      - PMA_HOSTS={{your_host}}_db_1
      - PMA_USER=magento
      - PMA_PASSWORD=magento
      - PMA_ABSOLUTE_URI=http://phpmyadmin.{{your_host}}.test
    labels:
        traefik.enable: "true"
        traefik.http.routers.{{your_host}}-phpmyadmin.rule: Host(`phpmyadmin.{{your_host}}.test`)
        traefik.http.routers.{{your_host}}-phpmyadmin.tls: "true"

if you are on linux edit your host file,
 127.0.0.1 phpmyadmin.{{your_host}}.test

**Comment by monteshot** [comment]
> May be helpful to add phpmyadmin,
> 
> docker pull phpmyadmin
> 
> add .warden/warden-env.yml file with the following code,
> 
> version: "2" services: phpmyadmin: restart: always image: docker.io/library/phpmyadmin:latest hostname: ${WARDEN_ENV_NAME}-phpmyadmin domainname: phpmyadmin.${WARDEN_ENV_NAME}.test ports: - 8000:80 environment: - PMA_HOSTS=${WARDEN_ENV_NAME}_db_1 - PMA_USER=magento - PMA_PASSWORD=magento - PMA_ABSOLUTE_URI=[http://phpmyadmin.${TRAEFIK_DOMAIN}](http://phpmyadmin.$%7BTRAEFIK_DOMAIN%7D) labels: traefik.enable: "true" traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.rule: Host(`phpmyadmin.${TRAEFIK_DOMAIN}`) traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.tls: "true"
> 
> if you are on linux edit your host file, 127.0.0.1 phpmyadmin.{{your_host}}.test

Who also want add PMA in warden and get traeifk error using the [comment](https://github.com/davidalger/warden/issues/193#issuecomment-992519113) [jomin-jolly](https://github.com/jomin-jolly) just use version "3.8" insead of "2"

**Comment by sanaeefar-saeed** [comment]
to add adminer do the following:
cd project_root
touch .warden/warden-env.yml
add these lines under the services section:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
open your browser
enter base_url:8080

**Comment by RakeshJesadiya** [comment]
@davidalger I got an error after upgrading Warden in Linux 20.04 for phpmyadmin.
I am able to connect it with CLI, via `warden db connect -A` but not from the browser.

Earlier I was able to access it via browser.
warden-env.yml file,
```
version: "3.5"
services:
  php-fpm:
    ports:
      - "4000:4000"
      - "3001:3001"
  phpmyadmin:
    restart: always
    image: docker.io/library/phpmyadmin:latest
    hostname: ${WARDEN_ENV_NAME}-phpmyadmin
    domainname: phpmyadmin.${WARDEN_ENV_NAME}.test
    ports:
      - 9200:80
    environment:
      - PMA_HOSTS=${WARDEN_ENV_NAME}_db_1
      - PMA_USER=magento
      - PMA_PASSWORD=magento
      - PMA_ABSOLUTE_URI=http://phpmyadmin.${TRAEFIK_DOMAIN}
```

Error Snapshot:
![phpmyadmin](https://user-images.githubusercontent.com/18594535/235077116-c2a881d5-68fd-433e-b7cb-b6bdce6f9be2.jpg)
