### ISSUE TITLE
Document how to configure per-project php-fpm settings by adding a custom .ini file to the project

### ISSUE THREAD

**Issue by davidalger** [davidalger/warden#198]
Example scenario (paths relative to project root):

* Create `.warden/php/zz-config.ini` - Place your custom config in this file.  the zz means its the last config file to load
* Create `.warden/warden-env.yml`

```
version: "3.5"
services:
  php-fpm:
    volumes:
      - ./.warden/php/zz-config.ini:/etc/php.d/zz-config.ini
  php-debug:
    volumes:
      - ./.warden/php/zz-config.ini:/etc/php.d/zz-config.ini
```

Alternate scenario would be overriding the `/etc/php.d/01-php.ini` file which is the file in which Warden container images place custom settings, with the following defaults currently:

```
date.timezone = UTC
max_execution_time = 3600
max_input_vars = 10000
memory_limit = 2G
display_errors = On
post_max_size = 25M
session.auto_start = Off
upload_max_filesize = 25M
```
