### ISSUE TITLE
Enabling MySQL slow query log

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#281]
Am looking for way to enable MySQL slow query log, is there a way I can enable the query logging through configuration or I can directly edit the Db container my.cnf file?

Any help/support is greatly appreciated, please help!

**Comment by Den4ik** [comment]
@Elamurugan-Nallathambi 
You may attach additional config via `.warden/.warden-env.yml` file at the project root folder with next content
```
version: "3.5"
services:
  db:
    volumes:
      - .${WARDEN_WEB_ROOT:-}/.warden/mysql/slow-query.cnf:/etc/mysql/conf.d/slow-query.cnf:cached

```
and config file `.warden/mysql/slow-query.cnf`
```
[mariadb]
slow_query_log
slow_query_log_file=/tmp/slow-queries.log
long_query_time=5.0
```
