### ISSUE TITLE
How can I custom the magento2.conf nginx 

### ISSUE THREAD

**Issue by oreales** [davidalger/warden#325]
I am trying without success to tweak te nginx.conf used in a Magento2 project. How can this be done? I have modified the magento2.conf in images/nginx/context/etc/nginx/available.d and warden env up --force-recreate but nginx conf is not changing. How can I achieve this. I am runing a Magento2 with storeviews in subdirectories and I am needing to introduce some locations in nginx to make them work. 

Any Help? Any Clue? I have not too much experience with docker / warden. Any help would be much appreciated.

**Comment by craft-tyler** [comment]
@oreales I just did this recently... It's pretty easy to do...

**Step 1: Update warden-env.yml** 
`.warden/warden-env.yml`
```
services:
    nginx:
        volumes:
            - ./.warden/nginx/nginx.conf:/etc/nginx/available.d/magento2.conf
```

**Next add your new nginx.conf**
`.warden/nginx/nginx.conf`

Will need to spin down the warden container and spin it back up for the changes to take effect.
