### ISSUE TITLE
Customize PHP-FPM container with some additional PHP Extensions

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#419]
How to customize `php-fpm` container so that I can load additional PHP extensions like MongoDB, etc.?

I can see that you can customize the PHP ini-settings via `./.warden/warden-env.yml`. 
But how to install the custom PHP extensions is my requirement.

Thanks

**Comment by tdgroot** [comment]
@MagePsycho You can install the PHP MongoDB extension as follows:

``` bash
warden env exec php-fpm sudo dnf install -y php-pecl-mongodb
warden env exec php-debug sudo dnf install -y php-pecl-mongodb
# for blackfire, if you use that
warden env exec php-blackfire sudo dnf install -y php-pecl-mongodb
```

**Comment by MagePsycho** [comment]
@tdgroot Thanks for the tips (one of the solution).

But with this, when you restart your OS or stop/destroy the services, for example:
```
# stop services
warden env stop

# destroy volumes
warden env down -v
```

You have to again re-execute those commands after you run
```
warden svc up
```

Not sure if we can override the `php-fpm` image with the custom one extending from php-fpm but has additional `mongodb` extension.

**Comment by lbajsarowicz** [comment]
@MagePsycho If you need to permanently build extended `php-fpm` image, I recommend creating your own `Dockerfile` for each of the Images and add the commands mentioned by @tdgroot there. You won't lose the adjustments when you restart services.

**Comment by MagePsycho** [comment]
@lbajsarowicz Thanks for your reply.

I have seen that you can easily replace the `db` image of MariaDB by MySQL as:
```
# File: ./.warden/warden-env.yml

services:
  db:
    image: docker.io/wardenenv/mysql:5.7
```

So after you create a custom image, a similar thing needs to be done?
```
version: "3.5"
services:
  php-fpm:
    image: my-custom-php-fpm
```

**Comment by MagePsycho** [comment]
> ```shell
> warden env exec php-fpm sudo dnf install -y php-pecl-mongodb
> ```

The command is not working
> sudo: dnf: command not found

**Comment by tdgroot** [comment]
@MagePsycho i think your images/containers are out of date. Update them using following commands.
```
warden env pull
warden env up
```

**Comment by ivan-veres** [comment]
@MagePsycho 

modify `warden-env.yml`

```
version: "3.5"

services:
  php-fpm:
    build:
      context: ./.warden/php-fpm
```

(contex begins where you have .env file)

in the `.warden/php-fpm` folder put your modified `Dockerfile`

Docker file should be something like this if you are using M2 image e.g.

```
FROM docker.io/wardenenv/php-fpm:7.2-magento2

<your modifications here>
```

Hope this helps.

**Comment by MagePsycho** [comment]
@ivan-veres I think this is what I was looking for.

Something like this?  
File: `.warden/php-fpm/Dockerfile`

```
FROM docker.io/wardenenv/php-fpm:7.2-magento2
dnf install -y php-pecl-mongodb
```

**Comment by ivan-veres** [comment]
@MagePsycho 

correct..

![Dockerfile](https://user-images.githubusercontent.com/5970595/133067534-a2965f13-233d-4b8e-8d50-e2fe84787c5e.png)

After that run `warden env build`

![env_build](https://user-images.githubusercontent.com/5970595/133067640-bef81fa5-7c9c-4d8f-a1ed-5362cb2253e1.png)
![env_build2](https://user-images.githubusercontent.com/5970595/133067662-02ee3b26-1453-4b17-8ede-ff8a08917083.png)

and `warden env up`

![env_up](https://user-images.githubusercontent.com/5970595/133067707-301e5304-f408-4a3c-a141-fb0a932c1a7a.png)

check phpinfo.

![phpinfo](https://user-images.githubusercontent.com/5970595/133067734-d6ad51b3-6a8d-47d2-ac28-02163dfc27a1.png)

**Comment by MagePsycho** [comment]
@ivan-veres That's for the detailed solution. Kudos!

**Comment by ivan-veres** [comment]
@MagePsycho yes, I forgot to mention that.

**Comment by MagePsycho** [comment]
@ivan-veres I am getting the following error
> Unsupported config option for services.mongo-db: 'php-fpm'

**Comment by ivan-veres** [comment]
@MagePsycho can you give more info? Where error is happening and what are you doing to cause this?

**Comment by MagePsycho** [comment]
I am trying to create a new project with the following warden file structure:
```
.
├── .env
└── .warden
    ├── php-fpm
    │   └── Dockerfile
    └── warden-env.yml

```
And `.warden/warden-env.yml` looks like this
```
version: "3.5"
services:
  db:
    image: docker.io/wardenenv/mysql:5.7
  mongo-db:
    image: 'mongo:4.0.25'
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./data/mongo:/data/db
    php-fpm:
      build:
        context: ./.warden/php-fpm
```
And now when I run either any of the commands below
```
warden env up
# or
warden env build
```
I get the following error:

> ERROR: The Compose file '.warden/warden-env.yml' is invalid because:
> Unsupported config option for services.mongo-db: 'php-fpm'

Note that I using Warden version 0.12.0
