### ISSUE TITLE
Custom nginx file not working

### ISSUE THREAD

**Issue by rbouma** [davidalger/warden#446]
The directory `/etc/nginx/default.d` does not exists in the nginx image so according to the docs: https://docs.warden.dev/environments/customizing.html#nginx-specific-customizations

The nginx container failed to start because of custom.conf that is binding to a directory that does not exists .

**Comment by ivan-veres** [comment]
You can change config by adding it in custom.conf

`version: "3.5"

services:

  nginx:
    hostname: nginx
    volumes:
      - ./.warden/nginx/conf.d/custom.conf:/etc/nginx/conf.d/custom.conf`

**Comment by rbouma** [comment]
@ivan-veres I know its in the docs. conf.d folder is not included as asteriks in de default.conf only default.d/* is included

**Comment by MagePsycho** [comment]
Why do you need to add custom files under `/etc/nginx/default.d`?
It can be simply linked to `/etc/nginx/conf.d/` folder as @ivan-veres has described.

**Comment by rbouma** [comment]
@MagePsycho I want to add a custom nginx location block for Magento 2.
Location block in nginx must be in the server block. as per https://github.com/davidalger/warden/blob/develop/images/nginx/context/etc/nginx/conf.d/default.conf#L16

inside this the only required configs are: 
```include /etc/nginx/available.d/${NGINX_TEMPLATE};``` which translate in include ```/etc/nginx/available.d/magento2.conf```
```include /etc/nginx/default.d/*.conf;```

@ivan-veres I cant place my configs there because its only included in the top http block in the nginx.conf. ```include /etc/nginx/conf.d/*.conf;``` I need this config in my server block.

The only configs from the server block are in ```include /etc/nginx/default.d/*.conf;```

And i can't redeclare server block with the same port 80 and 443.

I have fixed for now by overriding the whole magento2.conf en binding like this:
```
services:
  nginx:
    volumes:
      - ./.warden/nginx/magento2.conf:/etc/nginx/available.d/magento2.conf
 ```

**Comment by MagePsycho** [comment]
Just a note.
If you want to have a custom name other than `magento2.conf`m you can simply override in the warden settings as:
```
version: "3.5"
services:
  nginx:
    environment:
      NGINX_TEMPLATE: custom_magento2.conf
    volumes:
      - ./.warden/nginx/magento2.conf:/etc/nginx/available.d/custom_magento2.conf

```
