### ISSUE TITLE
How to use change the web index to other than index.php (ex: app.php)?

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#456]
I am working on some legacy Symfony projects which are using `app.php` as the entrypoint.
How would you override the Nginx settings so that it works for the `app.php` index?

So far, what I have done is
```
# File: .warden/warden-env.yml
version: "3.5"
services:
  nginx:
    environment:
      NGINX_PUBLIC: /web
    volumes:
      - ./.warden/nginx/custom.conf:/etc/nginx/default.d/custom.conf
```
Where `custom.conf` file looks like this:
```
index app.php;
```

With this change, till home, it works fine. But if you go to any inner pages it throws 404.
This is because we have this setting
```
# File: /etc/nginx/available.d/application.conf
location / {
    try_files $uri $uri/ /index.php$is_args$query_string;
}
```
If we change the above to below, it works fine.
```
location / {
    try_files $uri $uri/ /app.php$is_args$query_string;
}
```

**Question**: 
How can we override the above directive value in our local ` ./.warden/nginx/custom.con` file?
Or is there's any workaround for this?
