### ISSUE TITLE
Gettint "404 page not found"

### ISSUE THREAD

**Issue by se45ky** [davidalger/warden#541]
I just installed a fresh warden+magento2 installation, but I can't access the rabbitmq dashboard, the elastichsearch dashboard, or Magento front page.

- https://rabbitmq.magento2.test/
- https://magento2.test/
- https://elasticsearch.magento2.test/

I'm getting "404 page not found"

I already tried to stop and down everything, uninstall warden, uninstall docker, and install everything again from scratch, and still having the same issue.

Any thoughts?

My `.env` file:
```
WARDEN_ENV_NAME=magento2
WARDEN_ENV_TYPE=magento2
WARDEN_WEB_ROOT=/

TRAEFIK_DOMAIN="${WARDEN_ENV_NAME}.test"
TRAEFIK_SUBDOMAIN=app

WARDEN_DB=1
WARDEN_ELASTICSEARCH=1
WARDEN_VARNISH=0
WARDEN_RABBITMQ=1
WARDEN_REDIS=1

ELASTICSEARCH_VERSION=7.13
MARIADB_VERSION=10.3
NODE_VERSION=10
COMPOSER_VERSION=2
PHP_VERSION=8.1
PHP_XDEBUG_3=1
RABBITMQ_VERSION=3.9
REDIS_VERSION=6.2
VARNISH_VERSION=6.0

WARDEN_SYNC_IGNORE=

WARDEN_ALLURE=0
WARDEN_SELENIUM=0
WARDEN_SELENIUM_DEBUG=0
WARDEN_BLACKFIRE=0
WARDEN_SPLIT_SALES=0
WARDEN_SPLIT_CHECKOUT=0
WARDEN_TEST_DB=1
WARDEN_MAGEPACK=0

BLACKFIRE_CLIENT_ID=
BLACKFIRE_CLIENT_TOKEN=
BLACKFIRE_SERVER_ID=
BLACKFIRE_SERVER_TOKEN=
```

My `warden-env.yml`:

```
version: "3.5"
services:
  db:
    ports:
      - "3306:3306"
  elasticsearch:
    environment:
      - bootstrap.system_call_filter=false
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
  php-fpm:
    env_file:
      - .env
    volumes:
      - ../pub/git_info.txt:/pub/git_info.txt
      - ../pub//git_info.txt:/var/www/html/pub/git_info.txt
      - ../phpcs.xml:/var/www/html/phpcs.xml
  php-debug:
    env_file:
      - .env
    volumes:
      - ../pub/git_info.txt:/pub/git_info.txt
      - ../pub//git_info.txt:/var/www/html/pub/git_info.txt
      - ../phpcs.xml:/var/www/html/phpcs.xml

```
