### ISSUE TITLE
Change selenium environment include to use hub/node configuration

### ISSUE THREAD

**Issue by davidalger** [davidalger/warden#67]
As configured currently selenium is using an all-in-one container, this would preclude multi-browser testing. Would like to see something like the following (i.e. hub and a chrome node) supported OOTB here (allowing environments to add additional nodes as needed).

```
  selenium-hub:
    container_name: ${WARDEN_ENV_NAME}_selenium-hub
    image: selenium/hub:3.141.59-titanium
    ports:
      - "4444:4444"
  selenium-chrome:
    container_name: ${WARDEN_ENV_NAME}_chrome
    image: selenium/node-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=false

```
Note this will require reform before dropping into place as it came from a sidecar stack.

cc @lbajsarowicz would be wonderful if you'd like to tackle this since you've got a working MFTM setup you could validate the changes with, otherwise I'll probably tackle it only if I have the time leading up to Warden 0.2.0 release.
