### ISSUE TITLE
[Question] How to mount addition path (volumes)? 

### ISSUE THREAD

**Issue by hoanglan87** [davidalger/warden#84]
Sorry for newbie question but I setup an magento 2 project and can't find any way to specify additional mount point?
For example I want to mount external 'media' folder into docker?

**Comment by davidalger** [comment]
@hoanglan87 Been out of pocket for a week on business travel. Sorry about the delay here. It's not well documented at this point, but Warden has a feature where two per-project YAML files are merged into the docker compose configuration:
https://github.com/davidalger/warden/blob/develop/commands/env.cmd#L46-L54

You can use these to amend or overwrite values in the base configuration. For example, one of my projects has the following in `.warden/warden-env.yml` in the project repository to mount some custom tooling into the fpm container:

```
version: "3.5"
services:
  php-fpm:
    ## add mounts to bring the project toolkit into the php-fpm container
    volumes:
      - ./tools/project-toolkit:/opt/project-toolkit
      - ./.warden/etc/profile.d/project-toolkit.sh:/etc/profile.d/project-toolkit.sh
      - ./.warden/.aws:/home/www-data/.aws
```

Also a little tip here: You can run `warden env config` to output the full rendered docker-compose configuration to inspect what's there before/after you make changes via per-project configuration files.
